### ISSUE TITLE
Version 1x of Stash

### ISSUE THREAD

**Issue by arnabwahid** [themebeans/stash#4]
Hi @richtabor, thanks for all the great themes you make. 
I Couldn't find previous releases of Stash on this repo.  **Please let me know if I can download the v1 of this theme from somewhere.** I want to make the current version look just like the old one. TIA.

**Comment by richtabor** [comment]
Hey @arnabwahid sorry I missed this! I actually don't have older versions of the theme readily available. Stash 1.0.X is quite old now.
