### ISSUE TITLE
No access to template pages

### ISSUE THREAD

**Issue by ckenst** [themebeans/stash#5]
There doesn't appear to be a way to create new pages based on built-in templates such as Archives. I don't see any way / option to select them in the editor.

I realized this after upgrading to WP 5+ and seeing that my own Archives page is broken: https://www.kenst.com/archives/

- Wordpress version: 5.3.2
- Stash Parent Theme with Stash Child Theme 
- Stash version 2.0.6

**Comment by richtabor** [comment]
Hey @ckenst, I'm kind of confused. What archive page are you attempting to access? There's actually not an archives template any longer, as Gutenberg blocks provide that functionality. I removed it in v2.0.0 of the theme, back in [Nov 2018](https://github.com/themebeans/stash/blob/master/changelog.txt#L44).

**Comment by ckenst** [comment]
@richtabor I still have an archives template, probably because I've been on stash for a while and have just been upgrading over time. 

1. This likely means this removal broke existing implementations. 
2. How do I switch to using Gutenberg blocks to provide it?

**Comment by richtabor** [comment]
> This likely means this removal broke existing implementations.

That's why I pushed a new major version on that release. Can you send me the template file then? And what version of Stash are you on? I'd like to test it and see why the older templates won't assign. 

There's are new `Archives` and `Categories` blocks that do just about the same thing.

**Comment by ckenst** [comment]
Oh awesome, I found the Archives block and fixed my page. I wasn't aware of migration related things like this. Are there other things to be aware of? (Or else I'll just stumble across them, lol)

**Comment by richtabor** [comment]
> I wasn't aware of migration related things like this. Are there other things to be aware of? (Or else I'll just stumble across them, lol)

There shouldn't be any other breaking changes. Typically a major release indicates some sort of breaking change.
